ERROR - 2023-07-05 07:33:20 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\pwl-pa\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\pwl-pa\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ketbar', 3306, '', 0)
#1 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\pwl-pa\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\pwl-pa\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\pwl-pa\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\pwl-pa\app\Controllers\Auth.php(42): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(934): App\Controllers\Auth->login()
#8 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pwl-pa\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\pwl-pa\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\pwl-pa\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\pwl-pa\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\pwl-pa\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\pwl-pa\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\pwl-pa\app\Controllers\Auth.php(42): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(934): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pwl-pa\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\pwl-pa\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-07-05 07:33:20 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(42): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->login()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\pwl-pa\\public\\index.php')
ERROR - 2023-07-05 07:33:30 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\pwl-pa\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\pwl-pa\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ketbar', 3306, '', 0)
#1 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\pwl-pa\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\pwl-pa\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\pwl-pa\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\pwl-pa\app\Controllers\Auth.php(42): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(934): App\Controllers\Auth->login()
#8 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pwl-pa\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\pwl-pa\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\pwl-pa\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\pwl-pa\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\pwl-pa\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\pwl-pa\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\pwl-pa\app\Controllers\Auth.php(42): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(934): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pwl-pa\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\pwl-pa\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-07-05 07:33:30 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(42): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->login()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\pwl-pa\\public\\index.php')
ERROR - 2023-07-05 07:33:42 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\pwl-pa\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\pwl-pa\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ketbar', 3306, '', 0)
#1 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\pwl-pa\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\pwl-pa\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\pwl-pa\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\pwl-pa\app\Controllers\Auth.php(42): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(934): App\Controllers\Auth->login()
#8 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pwl-pa\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\pwl-pa\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\pwl-pa\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\pwl-pa\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\pwl-pa\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\pwl-pa\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\pwl-pa\app\Controllers\Auth.php(42): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(934): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pwl-pa\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\pwl-pa\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-07-05 07:33:42 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(42): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->login()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\pwl-pa\\public\\index.php')
ERROR - 2023-07-05 07:35:06 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\pwl-pa\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\pwl-pa\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ketbar', 3306, '', 0)
#1 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\pwl-pa\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\pwl-pa\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\pwl-pa\system\BaseModel.php(1188): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\pwl-pa\app\Controllers\ImageController.php(18): CodeIgniter\BaseModel->paginate(6)
#7 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(934): App\Controllers\ImageController->index()
#8 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ImageController))
#9 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pwl-pa\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\pwl-pa\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\pwl-pa\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\pwl-pa\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\pwl-pa\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\pwl-pa\system\BaseModel.php(1188): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\pwl-pa\app\Controllers\ImageController.php(18): CodeIgniter\BaseModel->paginate(6)
#6 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(934): App\Controllers\ImageController->index()
#7 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ImageController))
#8 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pwl-pa\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\pwl-pa\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-07-05 07:35:06 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `images`', [], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1188): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\ImageController.php(18): CodeIgniter\BaseModel->paginate(6)
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ImageController->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ImageController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\pwl-pa\\public\\index.php')
ERROR - 2023-07-05 07:35:29 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\pwl-pa\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\pwl-pa\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ketbar', 3306, '', 0)
#1 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\pwl-pa\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\pwl-pa\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\pwl-pa\system\BaseModel.php(1188): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\pwl-pa\app\Controllers\ImageController.php(18): CodeIgniter\BaseModel->paginate(6)
#7 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(934): App\Controllers\ImageController->index()
#8 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ImageController))
#9 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pwl-pa\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\pwl-pa\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\pwl-pa\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\pwl-pa\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\pwl-pa\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\pwl-pa\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\pwl-pa\system\BaseModel.php(1188): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\pwl-pa\app\Controllers\ImageController.php(18): CodeIgniter\BaseModel->paginate(6)
#6 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(934): App\Controllers\ImageController->index()
#7 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ImageController))
#8 C:\xampp\htdocs\pwl-pa\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pwl-pa\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\pwl-pa\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-07-05 07:35:29 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `images`', [], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1188): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\ImageController.php(18): CodeIgniter\BaseModel->paginate(6)
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ImageController->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ImageController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\pwl-pa\\public\\index.php')
CRITICAL - 2023-07-05 08:37:21 --> Invalid file: "whatsapp_button.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('whatsapp_button.php')
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('whatsapp_button', [], true)
 3 APPPATH\Controllers\ImageController.php(132): view('whatsapp_button', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ImageController->sendWhatsApp()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ImageController))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\pwl-pa\\public\\index.php')
CRITICAL - 2023-07-05 08:42:44 --> Invalid file: "whatsapp_button.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('whatsapp_button.php')
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('whatsapp_button', [], true)
 3 APPPATH\Controllers\ImageController.php(132): view('whatsapp_button', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ImageController->sendWhatsApp()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ImageController))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\pwl-pa\\public\\index.php')
CRITICAL - 2023-07-05 08:43:49 --> Undefined variable $image
in APPPATH\Views\images\show.php on line 17.
 1 APPPATH\Views\images\show.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $image', 'C:\\xampp\\htdocs\\pwl-pa\\app\\Views\\images\\show.php', 17)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\pwl-pa\\app\\Views\\images\\show.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('images/show', [], true)
 5 APPPATH\Controllers\ImageController.php(132): view('images/show', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ImageController->sendWhatsApp()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ImageController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\pwl-pa\\public\\index.php')
